repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    stages: [commit]
  - id: end-of-file-fixer
    stages: [commit]
  - id: check-yaml
    stages: [commit]
  - id: check-json
    stages: [commit]
  - id: check-merge-conflict
    stages: [commit]
  - id: detect-private-key
    stages: [commit]
  - id: mixed-line-ending
    args: [--fix=lf]
    stages: [commit]
    description: Forces to replace line ending by the UNIX 'lf' character.
  - id: check-added-large-files
    args: [--maxkb=500]
    stages: [commit]
  - id: no-commit-to-branch
    args: [--branch, staging]
    stages: [commit]

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.33.0
  hooks:
  - id: markdownlint
    stages: [commit]

- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.42.1
  hooks:
  - id: commitizen
  - id: commitizen-branch
    stages: [commit-msg, push]

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.0.0-alpha.6
  hooks:
  - id: prettier
    types_or: [javascript]
    stages: [commit]
